### PR TITLE
UDP Associate support for socks5

### PR DESCRIPTION
**Pull request by lixin9311**
It can be verified using `python` and `netcat`.

`pip install PySocks`

```python
import socks
import socket

TARGET_IP = "10.33.33.120"
TARGET_PORT = 1234
MESSAGE = "Hello, UDP Associate!"

s = socks.socksocket(socket.AF_INET, socket.SOCK_DGRAM)
s.set_proxy(socks.PROXY_TYPE_SOCKS5, "localhost", 1080)
s.sendto(MESSAGE, (TARGET_IP, TARGET_PORT))
```

### CODE REVIEW

**Comment by hvonw** [comment]
Hello, thanks a lot for the commit. I've been waiting for this feature.

I think you missed it these ones:
//go version go1.9.1 linux/amd64
./main.go:120:4: undefined: socks.UDPEnabled
./tcp.go:50:15: undefined: socks.InfoUDPAssociate

**Comment by lixin9311** [comment]
@hvonw pls check your import path before compiling. If you clone my repo, everything goes to github.com/lixin9311/blabla, but the program will still try to import from the original repo.

**Comment by hvonw** [comment]
@lixin9311 My bad, It's ok now. Thanks again!

**Comment by riobard** [comment]
@lixin9311 Could you please send the PR to the stable repo? https://github.com/shadowsocks/go-shadowsocks2

**Pull request closed without merging**
